### ISSUE TITLE
Unresponsive

### ISSUE THREAD

**Issue by christosg88** [kmesbah/quickmanapp#1]
I click on the icon of the extension, it tries to open but closes instantly. The same with <kbd>Ctrl</kbd>+<kbd>Y</kbd>.

**Comment by christosg88** [comment]
Actually sometimes it works but others it doesn't. I might click it 10 times and not open and then the 11th it opens.

**Comment by kmesbah** [comment]
@christosg88 the extension used to inject its content scripts after the document had loaded. this is why it may have taken it a while to start. it injects them at document start now.

**Comment by christosg88** [comment]
Downloaded again (but still the same version) and the bug is still here. Should I wait for an updated version?

**Comment by kmesbah** [comment]
@christosg88 in case you had any pages that had been loaded before you load the extension itself into Google Chrome, you should refresh these pages in order for the extension to do its job (i.e., injecting its content scripts into these pages).

you don't need to refresh any pages if the extension was already loaded and enabled before you load these pages though!

**Comment by christosg88** [comment]
Thanks @kmesbah! That solved the problem! Marking the issue as closed!
